### ISSUE TITLE
Feature4 Unit Test propt Error

### ISSUE THREAD

**Issue by devrokket** [OSS-FILEBROWSER/pretty-git#49]
## 이슈 상황
```
test : git clone -> 테스트 경로에 이미 클론할 디렉터리 이름이 존재한다.
assert : 같은 이름이 존재한다는 오류 메세지를 띄운다.
```
테스트 진행 중 ... 

<img width="450" alt="스크린샷 2023-06-04 오후 2 11 51" src="https://github.com/OSS-FILEBROWSER/pretty-git/assets/96538554/dfb8aa9a-ade5-46cd-94c1-cd52a5908476">

위처럼 프롬프트 에러 메시지가 같은 이름이 존재한다고 나오지 않음.

아래는 백이 주고 있는 에러 메시지. 

```
Error[clonePublicRepoAPI]: Error: fatal: destination path 'devrokket' already exists and is not an empty directory.
```

## 요약
프론트에서 주고 있는 에러 메시지 수정 가능한지.

**Comment by dogmania** [comment]
해결함
